### PR TITLE
Update display.py

### PR DESCRIPTION
**Pull request by mizsha**
display: Rename display.DisplayBufferRef to display.DisplayRef used by lambda

https://github.com/esphome/esphome/pull/5002

### CODE REVIEW

**Comment by JonasSL** [comment]
This change would be very appreciated! @tiaanv when will you be able to merge this?

**Comment by guillempages** [comment]
I've created #9, which basically does the same as this PR, but in a conditional way, so that older ESPHome versions can still use this components (in case this is what's blocking @tiaanv from merging this)

**Comment by guillempages** [comment]
@mizsha @JonasSL, if you are currently using this repository with this PR, I advise you to switch to #10, since the upcoming 2023.12.0 release has another breaking change, which is fixed there (and it also includes a fix for this particular issue here).

**Comment by tiaanv** [comment]
suoerceeded

**Pull request closed without merging**
